### ISSUE TITLE
FEATURE REQUEST: PowerSploit dev branch

### ISSUE THREAD

**Issue by cyberfreaq** [mandiant/commando-vm#102]
**Would you like have a tool or script added? Please include a link**
PowerSploit dev branch
https://github.com/PowerShellMafia/PowerSploit/tree/dev

**Is your feature request related to a problem? Please describe.**
I know that the dev version of PowerView.ps1 is included but would suggest to include the whole PowerSploit dev branch. Changes have been made to many scripts, not only to PowerView (e.g. Get-GPPPassword, which has a parameter for searching the entire forest as well as some other improvements in the dev version).

**If related to a problem, describe the solution you'd like**
Include PowerSploit dev branch into the Fireeye Chocolatey repo.

**Comment by day1player** [comment]
@cyberfreaq the dev branch is already included 👍 

It should be in C:\Tools\PowerSploit\Recon .. You should see both PowerView.ps1 and PowerView_dev.ps1

**Comment by cyberfreaq** [comment]
I know that the dev version of PowerView.ps1 is included but would suggest to include the **_whole_** PowerSploit dev branch. Changes have been made to many scripts, not only to PowerView (e.g. Get-GPPPassword, which has a parameter for searching the entire forest as well as some other improvements in the dev version).

**Comment by day1player** [comment]
@cyberfreaq apologies, looks like I didnt read the issue carefully enough. I will reopen the issue and we will look to add this in the next update. Thank you!

**Comment by skollr34p3r** [comment]
We decided to go a different direction with PowerSploit and are using this fork: https://github.com/ZeroDayLab/PowerSploit

This is the package we chose: https://github.com/mandiant/VM-Packages/tree/main/packages/powersploit.vm

Please create an issue here if you have any further suggestions for packages: https://github.com/mandiant/VM-Packages/issues/new/choose
