### ISSUE TITLE
Exchange maaaaz impacket binaries for ropnop impacket binaries

### ISSUE THREAD

**Issue by xillwillx** [mandiant/commando-vm#125]
instead of from https://github.com/maaaaz/impacket-examples-windows which hasnt been updated in a few years, grab newer binaries from https://github.com/ropnop/impacket_static_binaries

**Comment by day1player** [comment]
Thank you! Will do!

**Comment by Menn1s** [comment]
We are no longer going to be including the static binaries for impacket because of their age. If we were to include static impacket binaries, it would need to become a repository we manage and we currently don't have the bandwidth for that. Thank you
