### ISSUE TITLE
Background not changed, Readme not on desktop

### ISSUE THREAD

**Issue by day1player** [mandiant/commando-vm#139]
For various reason the Config package may not have successfully installed on Commando. This is the package that sets the background, and makes several other changes to the VM for operability, so it is important to be installed. 

First, restart the VM and re-run the install script.

Second, if it is not fixed, install the config manually with the following command in an admin prompt:
```
cinst -y commandovm.win10.config.fireeye
```

**Comment by nos3curity** [comment]
We are currently working on the 3.0 release of Commando later this summer. This issue has been addressed in the dev branch.
