### ISSUE TITLE
commandovm.win10.config.fireeye package installs successfully but does not change background

### ISSUE THREAD

**Issue by day1player** [mandiant/commando-vm#150]
## **Issue**
There seems to be a bug in our reboot checking that causes the package to install "successfully" but does not make any changes to the system as shown below:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/37482972/86407521-709f4080-bc72-11ea-91f7-e57be1cc0304.png">
Note that the logging provides an error message and causes the rest of the package to fail, but chocolatey considers this package as installing successfully.

## **Solution**
Restart your machine and force reinstall the config package:
```
cinst -y commandovm.win10.config.fireeye -f
```

**Comment by dkorzhevin** [comment]
![image](https://user-images.githubusercontent.com/762235/95609669-bfc1f200-0a67-11eb-8207-2a1361b80966.png)

**Comment by bajanray** [comment]
I tried the force reinstall config command that you suggested as a solution but I am still getting no changes made to the system.  
Attached is my chocolatey.log

[chocolatey.log](https://github.com/mandiant/commando-vm/files/7247921/chocolatey.log)

**Comment by day1player** [comment]
@bajanray did you reboot?

**Comment by day1player** [comment]
@bajanray what version of Windows are you on? Could you tell me if there are shortcuts on the desktop? Is your hostname changed to Commando? If you type `ping` does it use the python version or actual ping?

**Comment by bajanray** [comment]
1.  I'm on Windows 10 Enterprise - Version 21H1
  2.  Yes, there is shortcuts on the desktop.  A Tools folder that is empty, Recycle Bin, This PC icon and two hidden desktop.ini files
  3.  My hostname is not changed to Commando
  4.  When I type ping, it uses the actual ping.  Not the python version.

________________________________

**Comment by day1player** [comment]
@bajanray interesting, it seems like the entire install failed. I would restart at the beginning running the `install.ps1` script

**Comment by bajanray** [comment]
So, I went back to my snapshot at the very beginning and double checked to make sure that Windows Defender was disabled and the group policy setting to disable Windows Defender was not turned on.  So, I turned it on and made sure that no reboots were pending from Windows Updates and then ran the install.ps1 script.

It got further in the install process than before but then afterwards it just failed saying it couldn't install one of the Install-Obfuscation PowerShell scripts.  Checked the chocolatey log and it said my anti-virus stopped the install.  Sure, enough Windows Defender's real-time monitoring was turned back on for some reason and was blocking a whole bunch of the offensive PowerShell scripts.

I had to finally suspend the MsMpEng service and turn back on the disable Windows Defender group policy setting, reboot and then re-run the install script and it finally completed successfully.

I don't know why this install script gave me so much trouble.  I have used the Flare-VM install script using the same Windows 10 version build and it didn't give me any problems.

Thanks for all of your help.
bajanray
________________________________

**Comment by day1player** [comment]
Honestly there is a lot more "malware" on the Commando-VM build than there is on Flare-VM, and Defender is a total PITA.. Defender used to be able to be disabled with a powershell script, but recently with Tamper Protection it turns itself back on, and somehow even that seems to have gotten worse. The only reliable way to disable it currently is through Group Policy, and is described [here](https://github.com/mandiant/commando-vm#pre-install-procedures). Which is also why the recent install script has checks to make sure the service is not running. It is rather annoying, no doubt. Glad you were able to figure it out in the end 😄

**Comment by bajanray** [comment]
Yes, I concur that Defender is indeed a PITA...lol.  Thanks for your quick responses and all of your help.
________________________________

**Comment by skollr34p3r** [comment]
We have not seen this issue in a while, so closing.
