### ISSUE TITLE
Add support for PoshC2_Python

### ISSUE THREAD

**Issue by riskydissonance** [mandiant/commando-vm#16]
https://github.com/nettitude/PoshC2 is no longer maintained (see the readme), instead an official python edition has been created and is now far further ahead than the original build: https://github.com/nettitude/PoshC2_Python/

As python is already being installed, please consider using this version which is more fully featured and up-to-date.

**Comment by day1player** [comment]
Added to Roadmap

**Comment by Menn1s** [comment]
Because of the age of PoshC2 we do not plan to include this package. We are looking to include more popular C2s and leaving more specific C2s to be installed by the user.

If you would still like this package, consider creating an issue in the https://github.com/mandiant/VM-Packages repo.
