### ISSUE TITLE
BUG - spiderfoot.docker chocolatyuninstall not working.

### ISSUE THREAD

**Issue by jfmaes** [mandiant/commando-vm#201]
**Describe the bug and expected behavior**
chocolaty doesnt uninstall spiderfoot.docker.fireeye, seems to be related to the chocolatyuninstall script not dealing with ' " correctly.

**To Reproduce**
* open elevated prompt
* choco uninstall spiderfoot.docker.fireeye

**Screenshots**
![spiderfoot](https://user-images.githubusercontent.com/55604242/112964229-6b5f1b80-9148-11eb-9e0c-a77b563573b7.JPG)

**Version**
 - OS: Win 10

**Additional context**

**Comment by skollr34p3r** [comment]
Uninstall scripts are best effort. Thanks for letting us know about the issue.
