### ISSUE TITLE
Several packages failing to install

### ISSUE THREAD

**Issue by Grezzo** [mandiant/commando-vm#266]
The following packages fail installation:

- Invoke-Phant0m.fireeye: A checksum doesn't match
- Mimikatz.fireeye: The release that is attempted to be downloaded from GitHub is no longer available (HTTP 404)
- orca: A cab file from Microsoft is no longer available (HTTP 404)
- PSAttack.fireeye: PSAttack seems to have gone complletely from GitHub (HTTP 404)
- ruby2.devkit: An exe that should be dowloaded is no longer available (HTTP 404)
- SharpHound.fireeye: An zip file that should be dowloaded is no longer available (HTTP 404)

I assume orca and ruby2.devkit are not under your control. I wanted to try to fix the broken fireeye packages, but I can't find the source repository in order to update them and create a pull request. Is this something I can help with, or are those packages not community-updatable?

**Comment by day1player** [comment]
@Grezzo we are working at open-sourcing all of the fireeye packages currently. We are targetting to have them all released before the end of the year but until then it's kind of up to us to get them all fixed. I have noted all of these and they are on the chopping block :-)

**Comment by Chris3606** [comment]
Don't know if it's worth mentioning here, or a separate issue; however vcpython27 is also failing now; Microsoft has pulled the download link for that package.

**Comment by stabuu** [comment]
hello, 
just thought I ask if the packages are still being worked on I am getting failures on the following:

Failures
 - threadcontinue.fireeye (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\ThreadContinue.fireeye\Tools\chocolateyInstall.ps1'.
 See log for details.
 - sharphound.fireeye (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\SharpHound.fireeye\Tools\chocolateyInstall.ps1'.
 See log for details.
 - psattack.fireeye (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\PSAttack.fireeye\Tools\chocolateyInstall.ps1'.
 See log for details.
 - invoke-phant0m.fireeye (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\Invoke-Phant0m.fireeye\Tools\chocolateyInstall.ps1'.
 See log for details.
 - poshc2.fireeye (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\PoshC2.fireeye\Tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by tbarrettjr93** [comment]
> @Grezzo we are working at open-sourcing all of the fireeye packages currently. We are targetting to have them all released before the end of the year but until then it's kind of up to us to get them all fixed. I have noted all of these and they are on the chopping block :-)

I made a new bug post before seeing this....I've added the links to the ones that i could find to maybe make it a little easier to update.

**Comment by Menn1s** [comment]
Hi all, we are releasing Commando 3.0 and with it, all of Commando-VM packages have been open-sourced to the https://github.com/mandiant/VM-Packages repo.

We currently have fixed versions of sharphound and mimikatz, but the other packages have not been put on the todo list yet. If you would like to see specific packages, please create an issue on https://github.com/mandiant/VM-Packages.
