### ISSUE TITLE
To remove Apple Webkits

### ISSUE THREAD

**Issue by Apogee1776** [mandiant/commando-vm#268]
**Would you like have a tool or script added? Please include a link**
Name of the tool requested and a link to the tool webkit remover 

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem.  Apple webkits install script to attempt to block offline router access from MacBooks 

**If related to a problem, describe the solution you'd like**
Reveal and Remove webkit code 

**Describe alternatives you've considered**
Prevent from allowing Apple Webkits from reapplying router blocking code. 

**Additional context**
How discovered New Netgear Nighthawk routers are software coded can to dual route our data direct to ISP with scripted IPs and media storage if removed will be detected it would be better to find a way to collect data on the ISP trying to collect on all of us illegally then submit this to the Media

**Comment by day1player** [comment]
@Apogee1776 does this have to do with Commando-VM?
