### ISSUE TITLE
Chocolateyinstall.ps1 Fails while installing

### ISSUE THREAD

**Issue by SiddaDev** [mandiant/commando-vm#269]
While Installing, after the chocolateyinstall.ps1 starts the packages doesn't install and exits with incomplete installation

**Comment by day1player** [comment]
@SiddaDev do you know what package failed? we use chocolateyinstall.ps1 for all of our packages, there should be some more verbose logging somewhere.

**Comment by SiddaDev** [comment]
All the packages failed to install from chocolateyinstall.ps1 and suddenly the setup exits I will put up the logs if needed

**Comment by day1player** [comment]
@SiddaDev did you run the script with admin? Could you just send me a screen shot of what you are trying to do?

**Comment by Flangvik** [comment]
Having this exact issue as well. All packages fails to install with what looks to be the same error code
![2021-11-10_17-47-32](https://user-images.githubusercontent.com/23613997/141156216-af659e98-0854-48c7-9329-0ba5e1590bb9.png)

**Comment by Flangvik** [comment]
Attached is the boxstarter.log
[boxstarter.log](https://github.com/mandiant/commando-vm/files/7514495/boxstarter.log)

**Comment by ejawhary** [comment]
I have the same issue

**Comment by ejawhary** [comment]
Hi, Just wondering if there is any workaround for this. Thanks.

**Comment by nos3curity** [comment]
We've redone the affected Inveigh package in the new release of Commando scheduled for later this Summer. Thanks for bringing this up.
