### ISSUE TITLE
Rubeus.fireeye package does not save tool to C:\Tools directory

### ISSUE THREAD

**Issue by day1player** [mandiant/commando-vm#270]
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/37482972/140064598-98e2e164-4744-4880-8c71-4e123ffd93fd.png">

**Comment by day1player** [comment]
It's actually in C:\Tools\Ghostpack along with Seatbelt, etc.

Will probably move to C:\Tools

**Comment by nos3curity** [comment]
Fixed in the current dev branch with the updated Rubeus package.
