### ISSUE TITLE
run cinst -y ghidra.fireeye and not working 

### ISSUE THREAD

**Issue by s3cguy1990** [mandiant/commando-vm#271]
try to run cinst -y ghidra.fireeye and not working 
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://ghidra-sre.org/ghidra_9.2.2_PUBLIC_20201229.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
The install of ghidra.fireeye was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\ghidra.fireeye\tools\chocolateyinstall.ps1'.
 See log for details.

i try from "choco install ghidra" and that is work but not make a JDK attaching

**Comment by nos3curity** [comment]
Our upcoming 3.0 release shares packages with FlareVM. The Flare team has an updated Ghidra package that is accessible by Commando. The release is currently planned for later this Summer.
