### ISSUE TITLE
Pre-Install Procedures

### ISSUE THREAD

**Issue by fl0wmar** [mandiant/commando-vm#274]
Please add the following at the very beginning of the pre-install procedures

In newer versions of Windows, Group Policy settings for Microsoft Defender are reverted back.
To prevent this, before changing them:

Open Resource Monitor (type resmon.exe in the search box)
Overview
Find MsMpEng.exe in the list
Right-click > Suspend Process

**Comment by mattwilson21** [comment]
thanks this did help
