### ISSUE TITLE
Packages failed to Install - How to update package?

### ISSUE THREAD

**Issue by mnemonic-re** [mandiant/commando-vm#275]
Several packages failed to install:

Invoke-Phant0m.fireeye, Mimikatz.fireeye, orca, PSAttack.fireeye, ruby2.devkit, SharpHound.fireeye... 

**To Reproduce**
Ran the install as instructed and packages failed to install either due to 404 or checksum errors.

**Version**
 - OS: [Win10 x64 VMWare]

**Additional context**
I know you guys are busy and I appreciate that but if you could only help with how to update the packages so I can install them manually.
For example Mimikatz. It has 32bit and 64bit executable. Error is:

![mimikatz](https://user-images.githubusercontent.com/41833021/158056087-17d9be6e-5205-464a-b6cb-c25185e7f361.png)

I know the latest version is: https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20210810-2/mimikatz_trunk.7z

I am not that familiar with chocolatey. How do I update mimikatz link (package)? I tried modifying the chocolateyInstall.ps1 with new link, installed choco GUI and countless other things but it is always pulling from the same link - the broken one. If I were to able to fix mimikatz then I would probably fix all of them.

I just cannot find where original link is. I guess it is in sources on the fireeye site.

There is also a lot of really old software like x64dbg from july 2021. Cannot update further than that except manually.

Thank you.

**Comment by nos3curity** [comment]
The Commando 2.0 architecture required manual updates to packages. We've had an internal effort to change this and have automation in place thanks to the FlareVM team that will automatically update packages for us in 3.0. Our 3.0 release is planned for later this Summer.
