### ISSUE TITLE
BUG and Update plan

### ISSUE THREAD

**Issue by Itach1i** [mandiant/commando-vm#276]
Hello, is the update plan for the first quarter still as scheduled? Now that command-vm can't be installed on windows, after a point, enter will appear to end powershell, thank you for your answer.

**Comment by Antiseci** [comment]
++ Boxstarter finished Calling Chocolatey to install commandovm.win10.installer.fireeye. This may take several minutes to complete... 00:00:13.5989404
True
Boxstarter: Restore Automatic Updates from Windows Update
Boxstarter: Enabling UAC

**Comment by AnkurYogi** [comment]
Facing the same issue..!

**Comment by Antiseci** [comment]
> 面临同样的问题..！

真的很难受

**Comment by nos3curity** [comment]
The current main branch has several packages that are entirely broken. We've had a big effort this year to redo the installer from scratch and re-create and open-source all packages for Commando, coupled with automation that updates them. 

Standby for the 3.0 release coming later this Summer.
