### ISSUE TITLE
Grouper2 not found

### ISSUE THREAD

**Issue by yanghaoi** [mandiant/commando-vm#278]
Failures
 - grouper2.fireeye (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\Grouper2.fireeye\Tools\chocolateyInstall.ps1'.
 See log for details.

GROUPER2 IS DEPRECATED, GOTO https://github.com/Group3r/Group3r INSTEAD
This place is not a place of honor... no highly esteemed deed is commemorated here... nothing valued is here.
What is here was dangerous and repulsive to us. This message is a warning about danger.

**Comment by nos3curity** [comment]
We have created a package for Grouper3 in the 3.0 release of Commando coming later this Summer.
