### ISSUE TITLE
More Failed Installs

### ISSUE THREAD

**Issue by tbarrettjr93** [mandiant/commando-vm#279]
**Version**
 - OS: Win10 Pro 21H2 x64
  

Multiple failed installs. Mostly due to links that are no longer valid. Ive tried to add the current links that should be working that I've found. **If there is anything i can do to help solve these issues to make it easier on you guys please just let me know** .I think some of these are no longer available at all (ThreadContinue, sudomain-bruteforce, Grouper2)

Grouper2 - 404....project has been moved to Group3r...https://github.com/Group3r/Group3r/releases/download/1.0.13/Group3r.exe

hashcat - needs intel cpu....i have amd.. no worries there, i have it on my host pc.

impacket/libraries.python2.fireeye -  2022/06/29 17:05:37 [libraries.python2.fireeye] chocolateyinstall.ps1 [+] ERROR : Failed to install vivisect

Mimikatz - 404....needs updated url/hash 'https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20210810-2/mimikatz_trunk.7z'   ----sha256----  912DDCB057AE0B41311BE77A00AD2952AB1521C12FC712284A4FBFB58F1105BE

Proxycap.fireeye - downloads .msi but can open in notepad and see it is an html document.

PSAttack - 404 url no longer valid. do not see the prebuilt binaries on the github anymore.

rub2.devkit - 404 url no longer valid

SharpHound.fireeye - 404....found exe on BloodhoundAD 'https://github.com/BloodHoundAD/BloodHound/blob/master/Collectors/SharpHound.exe'

subdomain-bruteforce - 404...no longer a repository on visualbasic6 github

ThreadContinue.fireeye - 404 ....zerosum0x0 github no longer exist.

**Comment by mattwilson21** [comment]
I was thinking about trying to get this to work on Win11 - I can get a lot of get to go through but it does get stuck in a proxmox VM.   Is anyone planning to update this project ?

**Comment by 0xShkk** [comment]
Sad to see Commando seems abandoned. Did a clean install yesterday and realized a lot if outdated things. I would love to contribute an help keep Commando updated. Just let me know how.

**Comment by TylerJaacks** [comment]
any good alternatives, Flare VM is broken and a rewrite is currently in development

**Comment by nos3curity** [comment]
We are currently working on the 3.0 release of Commando coming later this summer. We've redone and open-sourced the majority of these packages, fixing the issues. Others are still in development. Standby for 3.0 :)

**Comment by tbarrettjr93** [comment]
> We are currently working on the 3.0 release of Commando coming later this summer. We've redone and open-sourced the majority of these packages, fixing the issues. Others are still in development. Standby for 3.0 :)

This is awesome news. Thank you! Looking forward to trying it out!
