### ISSUE TITLE
Providing the password doesn't work.

### ISSUE THREAD

**Issue by VaughanJ** [mandiant/commando-vm#280]
**Describe the bug and expected behavior**
I call `C:\tmp\commando-vm\install.ps1 -nochecks $true -password $NewAdminPassword -profile_file 'C:\tmp\commando-vm\Profiles\lite.json'' and the installation starts. At some point the OS restarts, I leave the installation a while assuming that it has auto logged on and the installation is running. When I log back in a prompt popups asking me for a password and then installation continues.

**To Reproduce**
1. Login to Windows OS
2. In Powershell as ADMIN, RUN 'C:\tmp\commando-vm\install.ps1 -nochecks $true -password $NewAdminPassword -profile_file 'C:\tmp\commando-vm\Profiles\lite.json''
3. Wait until the installation restarts.
4. Leave the installation running for 30 minutes by not logging in (assuming auto login has continued the installation)
5. Login 
6. See the problem when you are presented with a password prompt to continue the installation 

**Screenshots**
![image](https://user-images.githubusercontent.com/3703414/188837460-db2999e8-06d7-4ecb-b36f-84294594881b.png)

**Version**
 - OS: Microsoft Windows Server 2019 Datacenter

**Comment by D-808** [comment]
Try disabling password login - have no password needed to sign in. I think its best to do and then set a password once the installation has finished.

**Comment by nos3curity** [comment]
We are currently working on the 3.0 release of Commando later this summer. This issue is not present in the dev branch.
