### ISSUE TITLE
commando-vm 3.0 ???

### ISSUE THREAD

**Issue by PacifikPlant** [mandiant/commando-vm#281]
Hi team,

With the new (and awesome) release of the flare-vm, will you take the same road for a new release of the commando-vm?

I'm talking about the GUI and the VM-Package repo 🥹

**Comment by day1player** [comment]
@PacifikPlant yes! I think the Flare VM release was the kick in the pants we needed. We are now currently working on a new release! Targeting August of this year for completion.

**Comment by dkguy** [comment]
is Loving This Thing i am looking forward to the NeXT version

**Comment by IAMinZoho** [comment]
This is August. Any update on Commando 3.0? I am counting days here😋

**Comment by day1player** [comment]
@IAMinZoho you can start counting the minutes, we are presenting at Arsenal in about 3 hours and we will have it released before then :)

**Comment by day1player** [comment]
Released.

**Comment by IAMinZoho** [comment]
> @IAMinZoho you can start counting the minutes, we are presenting at Arsenal in about 3 hours and we will have it released before then :) 

Hats off to the entire team behind the Commando VM 3.0. I am very excited to play around. Thank you for the quick response. 🥰😇👌
