### ISSUE TITLE
mdefordownlevelserver install.ps1 errors

### ISSUE THREAD

**Issue by MikoAke** [mandiant/commando-vm#283]
Hi,
I ran the install.ps1 script from https://github.com/microsoft/mdefordownlevelserver/blob/main/Install.ps1 but it threw up loads of errors. The command I used was
 .\Install.ps1 -OnboardingScript ".\WindowsDefenderATPOnboardingScript.CMD"

The errors are
PS C:\365> .\Install.ps1 -OnboardingScript ".\WindowsDefenderATPOnboardingScript.CMD"
At C:\365\Install.ps1:209 char:17
+             Sign&nbsp;up
+                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\365\Install.ps1:214 char:209
+ ... k Button--medium Button d-lg-none color-fg-inherit p-1">    <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\365\Install.ps1:432 char:13
+       CI/CD &amp; Automation
+             ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\365\Install.ps1:1368 char:3
+  - old msis did not properly enumerate all the wmiprvse.exe processes ...
+   ~
Missing expression after unary operator '-'.
At C:\365\Install.ps1:1368 char:4
+  - old msis did not properly enumerate all the wmiprvse.exe processes ...
+    ~~~
Unexpected token 'old' in expression or statement.
At C:\365\Install.ps1:1372 char:87
+ ... -body d-flex flex-items-center flex-auto border-bottom-0 flex-wrap" >
+                                                                          ~
Missing file specification after redirection operator.
At C:\365\Install.ps1:1407 char:9
+ </a>    <a class="avatar-link" data-hovercard-type="user" data-hoverc ...
+         ~
The '<' operator is reserved for future use.
At C:\365\Install.ps1:1433 char:12
+       1438 lines (1342 sloc)
+            ~~~~~
Unexpected token 'lines' in expression or statement.
At C:\365\Install.ps1:1433 char:24
+       1438 lines (1342 sloc)
+                        ~~~~
Unexpected token 'sloc' in expression or statement.
At C:\365\Install.ps1:1433 char:23
+       1438 lines (1342 sloc)
+                       ~
Missing closing ')' in expression.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

See attached below

![ps](https://user-images.githubusercontent.com/128106610/225786558-9796f642-6193-4280-9b98-a1b48905c989.JPG)

**Comment by day1player** [comment]
Are you sure you're in the right repo? Fwiw I think you need to make sure when you download that script, you download "[raw](https://raw.githubusercontent.com/microsoft/mdefordownlevelserver/main/Install.ps1)", it looks like there is a bunch of HTML in your code.

**Comment by MikoAke** [comment]
Hi Day1player, thanks for your reply. Sorry to open this again. I'm very inexperienced with powershell and I appreciate any help you can offer. 
I used the [raw](https://raw.githubusercontent.com/microsoft/mdefordownlevelserver/main/Install.ps1) script you suggested to run .\Install.ps1 -OnboardingScript ".\WindowsDefenderATPOnboardingScript.CMD"

This is the result. Please can you tell me where I'm going wrong.
PS C:\365> .\Install.ps1 -OnboardingScript ".\WindowsDefenderATPOnboardingScript.CMD"
[ISH-DC1:03 23/03/17T22:02:26.402 Install.ps1:625] [Net.ServicePointManager]::SecurityProtocol updated to 'Ssl3, Tls, Tls12'
[ISH-DC1:03 23/03/17T22:02:27.090 Install.ps1:691] BuildLabEx: 14393.5717.amd64fre.rs1_release.230203-1742
[ISH-DC1:03 23/03/17T22:02:27.105 Install.ps1:693] EditionID: ServerStandard
[ISH-DC1:03 23/03/17T22:02:27.559 Install.ps1:695] 6117DD54BE35E7E651915936670EA17BE899A83026B66B78C6C54DB33F87CBCB C:\365\Install.ps1
[ISH-DC1:03 23/03/17T22:02:41.496 Install.ps1:279] 'HKCR' PSDrive created(script scoped)
[ISH-DC1:03 23/03/17T22:02:41.886 Install.ps1:1226] No etl file generated.
[ISH-DC1:03 23/03/17T22:02:41.902 Install.ps1:1233] No log file generated.
Invoke-Member : Exception calling "InvokeMember" with "5" argument(s): "OpenDatabase,DatabasePath,OpenMode"
At C:\365\Install.ps1:384 char:21
+ ...     $database = Invoke-Member $installer 'OpenDatabase' ($MsiPath, 0)
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Member], MethodInvocationException
    + FullyQualifiedErrorId : COMException,Invoke-Member

**Comment by MikoAke** [comment]
> Are you sure you're in the right repo? Fwiw I think you need to make sure when you download that script, you download "[raw](https://raw.githubusercontent.com/microsoft/mdefordownlevelserver/main/Install.ps1)", it looks like there is a bunch of HTML in your code.

Thank you! It looks like it is working
