### ISSUE TITLE
WinGet Prospects?

### ISSUE THREAD

**Issue by ElliotKillick** [mandiant/commando-vm#298]
WinGet is quite mainstream now and a lot of packages are available in the official Microsoft repositories. 

There's some notable benefits to WinGet such as:
- Most packages are maintained by their own upstream (this avoids the common issue of the Chocolatey package being out of date)
- A real packaging format (`MSIX`, in the same way Debian has `deb` and Fedora has `rpm` files)
    - MSIX is supported all the way back to Windows 7 through [MSIX Core](https://learn.microsoft.com/en-us/windows/msix/msix-core/msixcore)
- Comes installed on Windows by default (through App Installer) and officially supported by Microsoft

The only con I can think of is that I don't think WinGet supports Windows 8/8.1. However, that version of Windows has been out of support now for a while anyway. There may also be some packages used by Commando VM which haven't made their way to official WinGet repositories yet (this should probably be checked as the first step).

I'm just throwing the idea out there to get Commando VM's prospects on this matter. If a port is planned then it would probably take a decent amount of effort to get done. I've posted this same question on Flare VM's issue tracker.

Thanks!

**Comment by nos3curity** [comment]
We will look into this. Thank you so much for the suggestion. 

Our entire setup is quite tied to Chocolatey at this point, but we'll consider it for future updates.
