### ISSUE TITLE
ruby2.devkit error while downloading- website ceased to exist. could not be installed

### ISSUE THREAD

**Issue by payam59** [mandiant/commando-vm#303]
C:\Users\payam>choco install -y ruby2.devkit
Chocolatey v0.12.1
Installing the following packages:
ruby2.devkit
By installing, you accept licenses for the packages.
Progress: Downloading ruby2.devkit 4.7.2.2013022403... 100%

ruby2.devkit v4.7.2.2013022403 [Approved]
ruby2.devkit package files install completed. Performing other installation steps.
Get-BinRoot is going to be deprecated in v1 and removed in v2. It has been replaced with Get-ToolsLocation (starting with v0.9.10), however many packages no longer require a special separate directory since package folders no longer have versions on them. Some do though and should continue to use Get-ToolsLocation.
Chocolatey is installing DevKit to C:\Tools\DevKit2
Please wait...
Attempt to get headers for https://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading ruby2.devkit 64 bit
  from 'https://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe'
WARNING: Write-ChocolateyFailure is deprecated and will be removed in v2. If you are the package maintainer, please use 'throw $_.Exception' instead.
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The install of ruby2.devkit was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\ruby2.devkit\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

**Comment by day1player** [comment]
Any package not ending in `.fireeye` (deprecated/unsupported) or `.vm` (our new repo https://github.com/mandiant/VM-Packages) is not owned/maintained by us. You can check this package out here if you would like to find where to get it updated: https://community.chocolatey.org/packages/ruby2.devkit

Thank you very much for brining it to our attention :)
