### ISSUE TITLE
Waste of time, took me 2 days of trying to install. 

### ISSUE THREAD

**Issue by st1llz0r** [mandiant/commando-vm#304]
Uninstallable. Followed all the instructions. Trash stuff, don't waste time.

**Comment by st1llz0r** [comment]
simply stay far away from this if you dont want a headache and 30 hours of no sleep trying to fix errors back and forth in a loophole during a fking install. Sorry for my language, but was hyped when saw this and when realized is a kitch really exhausted me. why would you make something just to waste others ppl time?

**Comment by day1player** [comment]
@st1llz0r you can reach out to me here or if you're in the BloodHound slack feel free to dm me. We havent had any issues like this in any of our test installs. Please make sure you are meeting the prerequisites and installing on a supported platform.
