### ISSUE TITLE
Restarting install.ps1 to add additional packages results in Error

### ISSUE THREAD

**Issue by xplt-artur** [mandiant/commando-vm#316]
**Describe the bug and expected behavior**
After the initial install of lets say the "Default" package list, if I were to restart install.ps1 because I want to add additional packages, I get the following error

`
[+] Settings updated, beginning install. Please wait for a popup letting you know the installation is complete!
[+] Setting Boxstarter config
[!] Error: Failed to install profile:
The property 'RebootOk' cannot be found on this object. Verify that the property exists and can be set.
`

Which seems to be related to https://github.com/chocolatey/boxstarter/issues/380 and can be fixed by adding 
`
Import-Module Boxstarter.Chocolatey
`

**To Reproduce**
1. Install default commando VM via install.ps1
2. Start install.ps1 again, chose default preset, press install
3. See error

**Screenshots**
![image](https://github.com/mandiant/commando-vm/assets/116645364/ad66d0c3-9e10-4803-82b7-73cb989313c0)

**Version**
 - OS: Win10 22H2

**Comment by Menn1s** [comment]
Thanks @sh0ra1t! We're hoping this has been fixed with a couple changes made recently. not sure why the flag for noReboots would be set, but good to see a workaround.

**Comment by thearchivalone** [comment]
This bug reared it's head for me just yesterday on a fresh install on Windows 11 running VMWare 17.6.2 . sh0ra1t saved my install. Thanks

**Comment by sh0ra1t** [comment]
Only saw today these comments. 
Glad to know that I was able to help you 👍
