### ISSUE TITLE
Will this work on windows 11?

### ISSUE THREAD

**Issue by kism37** [mandiant/commando-vm#320]
**Would you like have a tool or script added? Please include a link**
Name of the tool requested and a link to the tool

**Is your feature request related to a problem? Please describe.**

**If related to a problem, describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Menn1s** [comment]
Windows 11 is currently not supported, so a number of tools will not be installed and certain changes applied in Windows 10 will not happen in Windows 11. 

There are some features still being worked on before we officially support Windows 11.

That being said, I do have it installed on my Windows 11 VM and it hasn't been an issue to use.
