### ISSUE TITLE
[Tool Request] FactionC2

### ISSUE THREAD

**Issue by itsreallynick** [mandiant/commando-vm#4]
Greetings distinguished Mandiant colleagues,

I don't know if the licensing allows it, but I am curious if CommandoVM would be able to implement [FactionC2](https://www.factionc2.com/) MARAUDER released at TROOPERS19; my understanding is it was developed by _one of the red team Jareds_ on twitter dot com.

I'm still getting caught up on CommandoVM's implementation of various command & control services, so I'll save similar questions for others like [byt3bl33d3r's SILENTTRINITY](https://github.com/byt3bl33d3r/SILENTTRINITY) for the future.

_Full disclosure: I am primarily interested in this because I like the logo (this is [well-documented](https://twitter.com/ItsReallyNick/status/1108891182598406144)) and because I'd like to find more diverse build servers & payloads in the wild. 😉_

**Comment by day1player** [comment]
Added to Roadmap

**Comment by fakename12345cat** [comment]
I thought Faction only works on ubuntu 18.02

**Comment by nos3curity** [comment]
The tool is no longer maintained. If you have requests for maintained C2 tools, please submit them. We'd love to get them into the upcoming 3.0 release!
